'use client';
import {Canvas,useFrame} from '@react-three/fiber';
import {OrbitControls,Environment,Text,Float,Stars} from '@react-three/drei';
import {Physics,RigidBody, CuboidCollider} from '@react-three/rapier';
import {useEffect,useRef} from 'react';
import * as THREE from 'three';
import type {Mode} from '@/lib/types';

function CityBlock({p=[0,0,0] as [number,number,number],s=[3,3,3] as [number,number,number]}){return <RigidBody type="fixed" colliders="cuboid" position={p}><mesh castShadow receiveShadow scale={s}><boxGeometry/><meshStandardMaterial color="#111a2d" metalness={.7} roughness={.35} emissive="#071224"/></mesh><mesh position={[0,s[1]/2+.02,0]}><boxGeometry args={[s[0]*.9,.04,s[2]*.9]}/><meshStandardMaterial color="#44e7ff" emissive="#44e7ff" emissiveIntensity={2}/></mesh></RigidBody>}
function Portal({position,label,color,onEnter}:{position:[number,number,number];label:string;color:string;onEnter:()=>void}){return <group position={position} onClick={onEnter}><mesh rotation={[0,Math.PI/2,0]}><torusGeometry args={[1.15,.08,16,64]}/><meshStandardMaterial color={color} emissive={color} emissiveIntensity={4}/></mesh><Text position={[0,1.55,0]} fontSize={.24} color="white" anchorX="center">{label}</Text></group>}
function Avatar({pos}:{pos:[number,number,number]}){const ref=useRef<THREE.Group>(null!);useFrame((_,d)=>{if(ref.current)ref.current.position.y=pos[1]+Math.sin(performance.now()/500)*.025});return <group ref={ref} position={pos}><mesh castShadow position={[0,.9,0]}><capsuleGeometry args={[.3,.8,8,16]}/><meshStandardMaterial color="#2d3d62" metalness={.3}/></mesh><mesh castShadow position={[0,1.55,0]}><sphereGeometry args={[.28,24,24]}/><meshStandardMaterial color="#f2b98c"/></mesh><mesh position={[0,1.62,.22]}><boxGeometry args={[.34,.05,.05]}/><meshStandardMaterial color="#44e7ff" emissive="#44e7ff" emissiveIntensity={3}/></mesh></group>}
function World({mode,onPortal}:{mode:Mode;onPortal:(m:Mode)=>void}){const keys=useRef<Record<string,boolean>>({});const pos=useRef(new THREE.Vector3(0,0,4));const avatar=useRef<THREE.Group>(null!);useEffect(()=>{const d=(e:KeyboardEvent)=>keys.current[e.key.toLowerCase()]=true;const u=(e:KeyboardEvent)=>keys.current[e.key.toLowerCase()]=false;addEventListener('keydown',d);addEventListener('keyup',u);return()=>{removeEventListener('keydown',d);removeEventListener('keyup',u)}},[]);useFrame((_,dt)=>{if(!avatar.current||mode!=='LOBBY')return;const k=keys.current;const v=new THREE.Vector3((k.d?1:0)-(k.a?1:0),0,(k.s?1:0)-(k.w?1:0));if(v.lengthSq()){v.normalize().multiplyScalar(dt*4);pos.current.add(v);pos.current.x=THREE.MathUtils.clamp(pos.current.x,-9,9);pos.current.z=THREE.MathUtils.clamp(pos.current.z,-9,9);avatar.current.position.lerp(pos.current,.45);avatar.current.rotation.y=Math.atan2(v.x,v.z)}});return <><Avatar pos={[0,0,4]}/><group ref={avatar} position={[0,0,4]}><Avatar pos={[0,0,0]}/></group><CityBlock p={[-5,1.5,-4]} s={[3,3,3]}/><CityBlock p={[5,1.5,-4]} s={[3,3,3]}/><CityBlock p={[-5,1.5,4]} s={[3,3,3]}/><CityBlock p={[5,1.5,4]} s={[3,3,3]}/><Portal position={[-5,1.4,-1]} label="RACING" color="#44e7ff" onEnter={()=>onPortal('RACING')}/><Portal position={[5,1.4,-1]} label="BATTLE" color="#ff3da7" onEnter={()=>onPortal('RACING')}/><Portal position={[0,1.4,-7]} label="TOURNAMENT" color="#ffd45a" onEnter={()=>onPortal('LEADERBOARD')}/><Text position={[0,2.2,0]} fontSize={.55} color="#eef5ff" anchorX="center">NEXUS CITY</Text></>}
function Track({onFinish}:{onFinish:()=>void}){const car=useRef<THREE.Group>(null!);const keys=useRef<Record<string,boolean>>({});const speed=useRef(0);const p=useRef(new THREE.Vector3(0,.45,7));useEffect(()=>{const d=(e:KeyboardEvent)=>keys.current[e.key.toLowerCase()]=true;const u=(e:KeyboardEvent)=>keys.current[e.key.toLowerCase()]=false;addEventListener('keydown',d);addEventListener('keyup',u);return()=>{removeEventListener('keydown',d);removeEventListener('keyup',u)}},[]);useFrame((_,dt)=>{if(!car.current)return;const k=keys.current;const throttle=k.w?1:0;const brake=k.s?1:0;speed.current+=throttle*dt*7-brake*dt*9-speed.current*dt*.65;speed.current=THREE.MathUtils.clamp(speed.current,-2,13);p.current.z-=speed.current*dt; if(k.a)p.current.x-=dt*4*(.4+Math.abs(speed.current)/10); if(k.d)p.current.x+=dt*4*(.4+Math.abs(speed.current)/10);p.current.x=THREE.MathUtils.clamp(p.current.x,-5,5);if(p.current.z<-13){p.current.z=7;onFinish()}car.current.position.copy(p.current);car.current.rotation.y=(k.a?.15:0)+(k.d?-.15:0)});return <><mesh rotation={[-Math.PI/2,0,0]} receiveShadow><planeGeometry args={[14,50]}/><meshStandardMaterial color="#151b28"/></mesh>{[-7,-3,1,5].map(x=><mesh key={x} position={[x,.02,-3]} rotation={[-Math.PI/2,0,0]}><planeGeometry args={[.08,42]}/><meshBasicMaterial color="#44e7ff"/></mesh>)}<group ref={car}><mesh castShadow><boxGeometry args={[1.5,.45,2.5]}/><meshStandardMaterial color="#e23b86" metalness={.8} roughness={.25} emissive="#4a0c2b"/></mesh>{[-.55,.55].flatMap(x=>[-.8,.8].map(z=><mesh key={`${x}${z}`} position={[x,-.3,z]} rotation={[Math.PI/2,0,0]}><cylinderGeometry args={[.24,.24,.18,16]}/><meshStandardMaterial color="#090b10"/></mesh>))}</group><Text position={[0,2,-14]} fontSize={.45} color="#44e7ff">FINISH LINE</Text></>}
export default function NexusWorld({mode,onPortal}:{mode:Mode;onPortal:(m:Mode)=>void}){return <Canvas shadows camera={{position:[0,7,11],fov:55}}><color attach="background" args={['#05060b']}/><ambientLight intensity={.45}/><directionalLight position={[5,10,5]} intensity={2} castShadow shadow-mapSize={[1024,1024]}/><Stars radius={80} depth={30} count={1200} factor={2} fade/><Environment preset="night"/><Physics gravity={[0,-9.81,0]}><CuboidCollider args={[30,.1,30]} position={[0,-.2,0]}/>{mode==='LOBBY'?<World mode={mode} onPortal={onPortal}/>:<Track onFinish={()=>onPortal('PROFILE')}/>}</Physics><OrbitControls enablePan={false} enableZoom={true} maxPolarAngle={Math.PI*.48} minDistance={7} maxDistance={20}/></Canvas>}
